# Add 'android' label to any changes within the 'app' folder
android:
  - changed-files:
      - any-glob-to-any-file: 'flutter_app/android/**'

# Add 'kotlin' label to any changes to Kotlin files
kotlin:
  - changed-files:
      - any-glob-to-any-file: '**/*.kt'

# Add 'gradle' label to any changes to Gradle files
gradle:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.gradle'
          - '**/*.gradle.kts'

# Add 'xml' label to any changes to XML files
xml:
  - changed-files:
      - any-glob-to-any-file: '**/*.xml'

# Add 'documentation' label to any changes to markdown files
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'

# Add 'github' label to any changes to GitHub configuration files
github:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

# Add 'scripts' label to any changes to script files
scripts:
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**'
          - 'flutter_app/tool/**'

# Add 'tests' label to any changes to test files
tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*Test*'
          - '**/*test*'
