package com.frp.frp_app

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.nio.ByteBuffer
import java.security.KeyStore
import java.util.Arrays
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/** Encrypts configuration values with an app-private Android Keystore key. */
object SecureStringCodec {
    private const val KEYSTORE = "AndroidKeyStore"
    private const val KEY_ALIAS = "frp_config_storage_v1"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    internal const val MAX_PLAINTEXT_BYTES = 5 * 1024 * 1024
    private const val MAX_IV_BYTES = 16
    private const val GCM_TAG_BYTES = 16
    internal const val MAX_ENCODED_PAYLOAD_CHARS =
        ((1 + MAX_IV_BYTES + MAX_PLAINTEXT_BYTES + GCM_TAG_BYTES + 2) / 3) * 4

    @Synchronized
    private fun key(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        (keyStore.getKey(KEY_ALIAS, null) as? SecretKey)?.let { return it }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setRandomizedEncryptionRequired(true)
                .build()
        )
        return generator.generateKey()
    }

    fun encrypt(plainText: String): String {
        require(plainText.length <= MAX_PLAINTEXT_BYTES) {
            "Plaintext exceeds the 5 MiB limit"
        }
        val plainBytes = plainText.toByteArray(Charsets.UTF_8)
        var iv: ByteArray? = null
        var encrypted: ByteArray? = null
        var binaryPayload: ByteArray? = null
        try {
            require(plainBytes.size <= MAX_PLAINTEXT_BYTES) {
                "Plaintext exceeds the 5 MiB limit"
            }
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key())
            encrypted = cipher.doFinal(plainBytes)
            iv = cipher.iv
            require(iv.size in 12..MAX_IV_BYTES) { "Invalid IV generated by keystore" }
            binaryPayload = ByteBuffer.allocate(1 + iv.size + encrypted.size)
                .put(iv.size.toByte())
                .put(iv)
                .put(encrypted)
                .array()
            return Base64.encodeToString(binaryPayload, Base64.NO_WRAP)
        } finally {
            Arrays.fill(plainBytes, 0)
            iv?.let { Arrays.fill(it, 0) }
            encrypted?.let { Arrays.fill(it, 0) }
            binaryPayload?.let { Arrays.fill(it, 0) }
        }
    }

    fun decrypt(payload: String): String {
        require(payload.length in 1..MAX_ENCODED_PAYLOAD_CHARS) {
            "Encrypted payload size is invalid"
        }
        val bytes = Base64.decode(payload, Base64.NO_WRAP)
        var iv: ByteArray? = null
        var encrypted: ByteArray? = null
        var plainBytes: ByteArray? = null
        try {
            require(bytes.isNotEmpty()) { "Encrypted payload is empty" }
            require(bytes.size <= 1 + MAX_IV_BYTES + MAX_PLAINTEXT_BYTES + GCM_TAG_BYTES) {
                "Encrypted payload exceeds the 5 MiB limit"
            }
            val buffer = ByteBuffer.wrap(bytes)
            val ivSize = buffer.get().toInt() and 0xff
            require(ivSize in 12..MAX_IV_BYTES && buffer.remaining() >= ivSize + GCM_TAG_BYTES) {
                "Invalid IV or encrypted payload"
            }
            iv = ByteArray(ivSize).also(buffer::get)
            encrypted = ByteArray(buffer.remaining()).also(buffer::get)
            require(encrypted.size <= MAX_PLAINTEXT_BYTES + GCM_TAG_BYTES) {
                "Encrypted payload exceeds the 5 MiB limit"
            }
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key(), GCMParameterSpec(128, iv))
            plainBytes = cipher.doFinal(encrypted)
            require(plainBytes.size <= MAX_PLAINTEXT_BYTES) {
                "Plaintext exceeds the 5 MiB limit"
            }
            return plainBytes.toString(Charsets.UTF_8)
        } finally {
            Arrays.fill(bytes, 0)
            iv?.let { Arrays.fill(it, 0) }
            encrypted?.let { Arrays.fill(it, 0) }
            plainBytes?.let { Arrays.fill(it, 0) }
        }
    }
}
