plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

val releaseMinSdk = providers.environmentVariable("FRP_RELEASE_MIN_SDK").orNull?.let { raw ->
    require(raw.matches(Regex("[0-9]+"))) { "FRP_RELEASE_MIN_SDK must be an integer" }
    raw.toInt()
}
require(releaseMinSdk == null || releaseMinSdk >= 28) {
    "Production key rotation requires FRP_RELEASE_MIN_SDK >= 28"
}
val forbiddenGradleSigningVariables = listOf(
    "FRP_RELEASE_KEYSTORE_BASE64",
    "FRP_RELEASE_LINEAGE_BASE64",
    "FRP_RELEASE_STORE_FILE",
    "FRP_RELEASE_STORE_PASSWORD",
    "FRP_RELEASE_KEY_ALIAS",
    "FRP_RELEASE_KEY_PASSWORD",
    "FRP_RELEASE_CERT_SHA256",
)
require(forbiddenGradleSigningVariables.none { !System.getenv(it).isNullOrBlank() }) {
    "Gradle release signing is disabled; use the isolated release workflow"
}
val forbiddenInjectedSigningProperties = listOf(
    "android.injected.signing.store.file",
    "android.injected.signing.store.password",
    "android.injected.signing.key.alias",
    "android.injected.signing.key.password",
    "android.injected.signing.store.type",
)
require(
    forbiddenInjectedSigningProperties.none { name ->
        providers.gradleProperty(name).isPresent || !System.getProperty(name).isNullOrBlank()
    },
) {
    "Injected Gradle signing is disabled; use the isolated release workflow"
}
val productionAbi = "arm64-v8a"
val integrationTestAbi = providers.gradleProperty("frp.integrationTestAbi").orNull
val targetAbi = integrationTestAbi ?: productionAbi
val supportedBuildAbis = setOf(productionAbi, "x86_64")
require(targetAbi in supportedBuildAbis) {
    "Unsupported frp.integrationTestAbi: $targetAbi"
}

android {
    namespace = "com.frp.frp_app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId = "com.frp.frp_app"
        minSdk = releaseMinSdk ?: flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        // frpc-xudp currently publishes an Android binary for arm64 only.
        // Restrict installation so other ABIs cannot install a seemingly valid
        // APK that has no executable frpc core.
        ndk {
            abiFilters += setOf(targetAbi)
        }
    }

    buildTypes {
        debug {
            // Keep device tests isolated from an installed production package.
            applicationIdSuffix = ".debug"
        }
        release {
            // Every Gradle release artifact is deliberately unsigned. The
            // protected GitHub job validates the APK before loading its key.
            signingConfig = null
        }
    }

    if (integrationTestAbi == "x86_64") {
        // Generated by scripts/build_frpc_test_stub_android.sh. This source
        // directory is attached only to Debug instrumentation builds.
        sourceSets.getByName("debug").jniLibs.srcDir(
            file("../../build/frpc-test-stub"),
        )
    }

    // frpc 原生二进制需要从 nativeLibraryDir 解压后作为进程运行
    packaging {
        jniLibs {
            useLegacyPackaging = true
            // Both Go artifacts are already stripped reproducibly with -s -w.
            // Preserve their audited bytes so the isolated signing job can
            // verify the exact embedded hashes before it receives any key.
            keepDebugSymbols += setOf("**/libfrpc.so", "**/libfrpc_cert.so")
            // x86_64 is permitted only when explicitly requested by the CI
            // instrumentation task. That APK exercises Android/UI policy and
            // deliberately does not claim to contain a runnable frpc core.
            excludes += setOf("armeabi-v7a", "x86", "arm64-v8a", "x86_64")
                .filter { it != targetAbi }
                .map { "**/$it/*.so" }
        }
    }
}

dependencies {
    androidTestImplementation("androidx.test:core-ktx:1.7.0")
    androidTestImplementation("androidx.test:runner:1.7.0")
    androidTestImplementation("androidx.test.ext:junit-ktx:1.3.0")
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
