#!/bin/bash

# 手动下载frpc说明脚本
echo "=========================================="
echo "FRP Android - 手动下载frpc说明"
echo "=========================================="
echo ""
echo "由于网络问题，请手动下载frpc二进制文件："
echo ""
echo "1. 访问 https://github.com/fatedier/frp/releases"
echo "2. 下载 frp_0.51.3_linux_arm64.tar.gz"
echo "3. 解压后将 frpc 文件复制到 app/src/main/assets/frpc"
echo ""
echo "或者使用以下命令（如果有代理）："
echo ""
echo "# 设置代理"
echo "export http_proxy=http://YOUR_PROXY:PORT"
echo "export https_proxy=http://YOUR_PROXY:PORT"
echo ""
echo "# 下载"
echo "curl -L https://github.com/fatedier/frp/releases/download/v0.51.3/frp_0.51.3_linux_arm64.tar.gz -o frp.tar.gz"
echo ""
echo "# 解压"
echo "tar -xzf frp.tar.gz"
echo ""
echo "# 复制"
echo "cp frp_0.51.3_linux_arm64/frpc app/src/main/assets/"
echo ""
echo "=========================================="
