name: Auto Assignee
on:
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  auto-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: pozil/auto-assign-issue@af6beea6bdf1e8eb373f061c5bc168681fc6d011 # v4
        with:
          assignees: gbitcat
          numOfAssignee: 1
