name: Auto Settings
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  repository-projects: write

jobs:
  auto-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: matt-ball/settings-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'gbitcat/FRP-Android'
